// Mocks generated by Mockito 5.4.6 from annotations
// in todolist_flutter/test/habit_controller_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i11;

import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist_flutter/feature/habit/controllers/category_habit_controller.dart'
    as _i2;
import 'package:todolist_flutter/feature/habit/controllers/habit_controller.dart' as _i8;
import 'package:todolist_flutter/models/category_habit_entity.dart' as _i4;
import 'package:todolist_flutter/models/habit_entity.dart' as _i9;
import 'package:todolist_flutter/objectbox.g.dart' as _i5;
import 'package:todolist_flutter/services/api_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategoryHabitController_0 extends _i1.SmartFake
    implements _i2.CategoryHabitController {
  _FakeCategoryHabitController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_1<E> extends _i1.SmartFake implements _i3.RxList<E> {
  _FakeRxList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_2 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryHabitEntity_4 extends _i1.SmartFake
    implements _i4.CategoryHabitEntity {
  _FakeCategoryHabitEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryBuilder_5<T> extends _i1.SmartFake
    implements _i5.QueryBuilder<T> {
  _FakeQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTasks, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchPersons() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPersons, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchHabits() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHabits, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchCategoriesHabit() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoriesHabit, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [HabitController].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitController extends _i1.Mock implements _i8.HabitController {
  MockHabitController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryHabitController get categoryHabit =>
      (super.noSuchMethod(
            Invocation.getter(#categoryHabit),
            returnValue: _FakeCategoryHabitController_0(
              this,
              Invocation.getter(#categoryHabit),
            ),
          )
          as _i2.CategoryHabitController);

  @override
  _i3.RxList<_i9.HabitEntity> get habits =>
      (super.noSuchMethod(
            Invocation.getter(#habits),
            returnValue: _FakeRxList_1<_i9.HabitEntity>(
              this,
              Invocation.getter(#habits),
            ),
          )
          as _i3.RxList<_i9.HabitEntity>);

  @override
  _i3.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_2(this, Invocation.getter(#isLoading)),
          )
          as _i3.RxBool);

  @override
  _i3.RxList<_i9.HabitEntity> get displayedHabit =>
      (super.noSuchMethod(
            Invocation.getter(#displayedHabit),
            returnValue: _FakeRxList_1<_i9.HabitEntity>(
              this,
              Invocation.getter(#displayedHabit),
            ),
          )
          as _i3.RxList<_i9.HabitEntity>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFilterHabit() => super.noSuchMethod(
    Invocation.method(#applyFilterHabit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadsHabit() =>
      (super.noSuchMethod(
            Invocation.method(#loadsHabit, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void toggleHabitCompletion(_i9.HabitEntity? habit) => super.noSuchMethod(
    Invocation.method(#toggleHabitCompletion, [habit]),
    returnValueForMissingStub: null,
  );

  @override
  void verifyNameHabit(String? newTitle, int? categoryHabitId) =>
      super.noSuchMethod(
        Invocation.method(#verifyNameHabit, [newTitle, categoryHabitId]),
        returnValueForMissingStub: null,
      );

  @override
  bool addHabits({
    required String? title,
    String? description,
    required int? categoryHabitId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addHabits, [], {
              #title: title,
              #description: description,
              #categoryHabitId: categoryHabitId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: false,
          )
          as bool);

  @override
  void deleteHabit(_i9.HabitEntity? habit) => super.noSuchMethod(
    Invocation.method(#deleteHabit, [habit]),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListener(_i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i11.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListenerId(Object? key, _i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryHabitBox extends _i1.Mock
    implements _i5.Box<_i4.CategoryHabitEntity> {
  MockCategoryHabitBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(
    _i4.CategoryHabitEntity? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  _i7.Future<int> putAsync(
    _i4.CategoryHabitEntity? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAsync, [object], {#mode: mode}),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i4.CategoryHabitEntity> putAndGetAsync(
    _i4.CategoryHabitEntity? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
            returnValue: _i7.Future<_i4.CategoryHabitEntity>.value(
              _FakeCategoryHabitEntity_4(
                this,
                Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
              ),
            ),
          )
          as _i7.Future<_i4.CategoryHabitEntity>);

  @override
  _i7.Future<int> putQueuedAwaitResult(
    _i4.CategoryHabitEntity? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueuedAwaitResult, [object], {#mode: mode}),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  int putQueued(
    _i4.CategoryHabitEntity? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueued, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  List<int> putMany(
    List<_i4.CategoryHabitEntity>? objects, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putMany, [objects], {#mode: mode}),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i7.Future<List<int>> putManyAsync(
    List<_i4.CategoryHabitEntity>? objects, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putManyAsync, [objects], {#mode: mode}),
            returnValue: _i7.Future<List<int>>.value(<int>[]),
          )
          as _i7.Future<List<int>>);

  @override
  _i7.Future<List<_i4.CategoryHabitEntity>> putAndGetManyAsync(
    List<_i4.CategoryHabitEntity>? objects, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetManyAsync, [objects], {#mode: mode}),
            returnValue: _i7.Future<List<_i4.CategoryHabitEntity>>.value(
              <_i4.CategoryHabitEntity>[],
            ),
          )
          as _i7.Future<List<_i4.CategoryHabitEntity>>);

  @override
  _i4.CategoryHabitEntity? get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id]))
          as _i4.CategoryHabitEntity?);

  @override
  _i7.Future<_i4.CategoryHabitEntity?> getAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAsync, [id]),
            returnValue: _i7.Future<_i4.CategoryHabitEntity?>.value(),
          )
          as _i7.Future<_i4.CategoryHabitEntity?>);

  @override
  List<_i4.CategoryHabitEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: <_i4.CategoryHabitEntity?>[],
          )
          as List<_i4.CategoryHabitEntity?>);

  @override
  _i7.Future<List<_i4.CategoryHabitEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManyAsync,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: _i7.Future<List<_i4.CategoryHabitEntity?>>.value(
              <_i4.CategoryHabitEntity?>[],
            ),
          )
          as _i7.Future<List<_i4.CategoryHabitEntity?>>);

  @override
  List<_i4.CategoryHabitEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i4.CategoryHabitEntity>[],
          )
          as List<_i4.CategoryHabitEntity>);

  @override
  _i7.Future<List<_i4.CategoryHabitEntity>> getAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAsync, []),
            returnValue: _i7.Future<List<_i4.CategoryHabitEntity>>.value(
              <_i4.CategoryHabitEntity>[],
            ),
          )
          as _i7.Future<List<_i4.CategoryHabitEntity>>);

  @override
  _i5.QueryBuilder<_i4.CategoryHabitEntity> query([
    _i5.Condition<_i4.CategoryHabitEntity>? qc,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [qc]),
            returnValue: _FakeQueryBuilder_5<_i4.CategoryHabitEntity>(
              this,
              Invocation.method(#query, [qc]),
            ),
          )
          as _i5.QueryBuilder<_i4.CategoryHabitEntity>);

  @override
  int count({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {#limit: limit}),
            returnValue: 0,
          )
          as int);

  @override
  bool isEmpty() =>
      (super.noSuchMethod(Invocation.method(#isEmpty, []), returnValue: false)
          as bool);

  @override
  bool contains(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool containsMany(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#containsMany, [ids]),
            returnValue: false,
          )
          as bool);

  @override
  bool remove(int? id) =>
      (super.noSuchMethod(Invocation.method(#remove, [id]), returnValue: false)
          as bool);

  @override
  _i7.Future<bool> removeAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  int removeMany(List<int>? ids) =>
      (super.noSuchMethod(Invocation.method(#removeMany, [ids]), returnValue: 0)
          as int);

  @override
  _i7.Future<int> removeManyAsync(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#removeManyAsync, [ids]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  int removeAll() =>
      (super.noSuchMethod(Invocation.method(#removeAll, []), returnValue: 0)
          as int);

  @override
  _i7.Future<int> removeAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllAsync, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}
