// Mocks generated by Mockito 5.4.6 from annotations
// in todolist_flutter/test/task_controller_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i12;

import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist_flutter/controller/category_controller.dart' as _i2;
import 'package:todolist_flutter/controller/person_controller.dart' as _i3;
import 'package:todolist_flutter/controller/task_controller.dart' as _i11;
import 'package:todolist_flutter/models/category_entity.dart' as _i7;
import 'package:todolist_flutter/models/person_entity.dart' as _i8;
import 'package:todolist_flutter/models/task_entity.dart' as _i5;
import 'package:todolist_flutter/objectbox.g.dart' as _i6;
import 'package:todolist_flutter/services/api_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategoryController_0 extends _i1.SmartFake
    implements _i2.CategoryController {
  _FakeCategoryController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonController_1 extends _i1.SmartFake
    implements _i3.PersonController {
  _FakePersonController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_2<E> extends _i1.SmartFake implements _i4.RxList<E> {
  _FakeRxList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_3 extends _i1.SmartFake implements _i4.RxBool {
  _FakeRxBool_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_4<T> extends _i1.SmartFake implements _i4.Rx<T> {
  _FakeRx_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_5<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_6 extends _i1.SmartFake implements _i4.RxInt {
  _FakeRxInt_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskEntity_7 extends _i1.SmartFake implements _i5.TaskEntity {
  _FakeTaskEntity_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryBuilder_8<T> extends _i1.SmartFake
    implements _i6.QueryBuilder<T> {
  _FakeQueryBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryEntity_9 extends _i1.SmartFake
    implements _i7.CategoryEntity {
  _FakeCategoryEntity_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonEntity_10 extends _i1.SmartFake implements _i8.PersonEntity {
  _FakePersonEntity_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i9.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTasks, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchPersons() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPersons, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchHabits() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHabits, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> fetchCategoriesHabit() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoriesHabit, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TaskController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskController extends _i1.Mock implements _i11.TaskController {
  MockTaskController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryController get categoryController =>
      (super.noSuchMethod(
            Invocation.getter(#categoryController),
            returnValue: _FakeCategoryController_0(
              this,
              Invocation.getter(#categoryController),
            ),
          )
          as _i2.CategoryController);

  @override
  _i3.PersonController get personController =>
      (super.noSuchMethod(
            Invocation.getter(#personController),
            returnValue: _FakePersonController_1(
              this,
              Invocation.getter(#personController),
            ),
          )
          as _i3.PersonController);

  @override
  _i4.RxList<_i5.TaskEntity> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: _FakeRxList_2<_i5.TaskEntity>(
              this,
              Invocation.getter(#tasks),
            ),
          )
          as _i4.RxList<_i5.TaskEntity>);

  @override
  _i4.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#isLoading)),
          )
          as _i4.RxBool);

  @override
  _i4.Rx<DateTime> get selectedFilterDate =>
      (super.noSuchMethod(
            Invocation.getter(#selectedFilterDate),
            returnValue: _FakeRx_4<DateTime>(
              this,
              Invocation.getter(#selectedFilterDate),
            ),
          )
          as _i4.Rx<DateTime>);

  @override
  _i4.RxList<_i5.TaskEntity> get displayedTasks =>
      (super.noSuchMethod(
            Invocation.getter(#displayedTasks),
            returnValue: _FakeRxList_2<_i5.TaskEntity>(
              this,
              Invocation.getter(#displayedTasks),
            ),
          )
          as _i4.RxList<_i5.TaskEntity>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyFilters() => super.noSuchMethod(
    Invocation.method(#applyFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool addTask({
    required String? title,
    String? description,
    required int? categoryId,
    required int? personId,
    _i12.Color? color,
    DateTime? date,
    String? startTime,
    String? endTime,
    bool? remindMe = false,
    String? link,
    String? photoPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [], {
              #title: title,
              #description: description,
              #categoryId: categoryId,
              #personId: personId,
              #color: color,
              #date: date,
              #startTime: startTime,
              #endTime: endTime,
              #remindMe: remindMe,
              #link: link,
              #photoPath: photoPath,
            }),
            returnValue: false,
          )
          as bool);

  @override
  void toggleCompleted(_i5.TaskEntity? task) => super.noSuchMethod(
    Invocation.method(#toggleCompleted, [task]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTask(_i5.TaskEntity? task) => super.noSuchMethod(
    Invocation.method(#deleteTask, [task]),
    returnValueForMissingStub: null,
  );

  @override
  void verifyNameTask(String? newTitle, int? categoryId) => super.noSuchMethod(
    Invocation.method(#verifyNameTask, [newTitle, categoryId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.TaskEntity? getTaskById(int? taskId) =>
      (super.noSuchMethod(Invocation.method(#getTaskById, [taskId]))
          as _i5.TaskEntity?);

  @override
  bool updateTaskTitle(
    int? taskId,
    String? newTitle,
    String? description,
    int? categoryId,
    int? personId,
    _i12.Color? color,
    DateTime? date,
    String? startTime,
    String? endTime,
    bool? remindMe,
    String? link,
    String? photoPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskTitle, [
              taskId,
              newTitle,
              description,
              categoryId,
              personId,
              color,
              date,
              startTime,
              endTime,
              remindMe,
              link,
              photoPath,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i12.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListenerId(Object? key, _i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryController extends _i1.Mock
    implements _i2.CategoryController {
  MockCategoryController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i7.CategoryEntity> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _FakeRxList_2<_i7.CategoryEntity>(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i4.RxList<_i7.CategoryEntity>);

  @override
  _i4.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#isLoading)),
          )
          as _i4.RxBool);

  @override
  _i4.RxInt get selectedCategoryId =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCategoryId),
            returnValue: _FakeRxInt_6(
              this,
              Invocation.getter(#selectedCategoryId),
            ),
          )
          as _i4.RxInt);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool addCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [name]),
            returnValue: false,
          )
          as bool);

  @override
  void selectCategory(int? categoryId) => super.noSuchMethod(
    Invocation.method(#selectCategory, [categoryId]),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i12.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListenerId(Object? key, _i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PersonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonController extends _i1.Mock implements _i3.PersonController {
  MockPersonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i8.PersonEntity> get persons =>
      (super.noSuchMethod(
            Invocation.getter(#persons),
            returnValue: _FakeRxList_2<_i8.PersonEntity>(
              this,
              Invocation.getter(#persons),
            ),
          )
          as _i4.RxList<_i8.PersonEntity>);

  @override
  _i4.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_3(this, Invocation.getter(#isLoading)),
          )
          as _i4.RxBool);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadPersons() =>
      (super.noSuchMethod(
            Invocation.method(#loadPersons, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool addPerson(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addPerson, [name]),
            returnValue: false,
          )
          as bool);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i12.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListenerId(Object? key, _i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskBox extends _i1.Mock implements _i6.Box<_i5.TaskEntity> {
  MockTaskBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(_i5.TaskEntity? object, {_i6.PutMode? mode = _i6.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  _i10.Future<int> putAsync(
    _i5.TaskEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<_i5.TaskEntity> putAndGetAsync(
    _i5.TaskEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<_i5.TaskEntity>.value(
              _FakeTaskEntity_7(
                this,
                Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i5.TaskEntity>);

  @override
  _i10.Future<int> putQueuedAwaitResult(
    _i5.TaskEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueuedAwaitResult, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int putQueued(
    _i5.TaskEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueued, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  List<int> putMany(
    List<_i5.TaskEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putMany, [objects], {#mode: mode}),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i10.Future<List<int>> putManyAsync(
    List<_i5.TaskEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<int>>.value(<int>[]),
          )
          as _i10.Future<List<int>>);

  @override
  _i10.Future<List<_i5.TaskEntity>> putAndGetManyAsync(
    List<_i5.TaskEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<_i5.TaskEntity>>.value(
              <_i5.TaskEntity>[],
            ),
          )
          as _i10.Future<List<_i5.TaskEntity>>);

  @override
  _i5.TaskEntity? get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id])) as _i5.TaskEntity?);

  @override
  _i10.Future<_i5.TaskEntity?> getAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAsync, [id]),
            returnValue: _i10.Future<_i5.TaskEntity?>.value(),
          )
          as _i10.Future<_i5.TaskEntity?>);

  @override
  List<_i5.TaskEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: <_i5.TaskEntity?>[],
          )
          as List<_i5.TaskEntity?>);

  @override
  _i10.Future<List<_i5.TaskEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManyAsync,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: _i10.Future<List<_i5.TaskEntity?>>.value(
              <_i5.TaskEntity?>[],
            ),
          )
          as _i10.Future<List<_i5.TaskEntity?>>);

  @override
  List<_i5.TaskEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i5.TaskEntity>[],
          )
          as List<_i5.TaskEntity>);

  @override
  _i10.Future<List<_i5.TaskEntity>> getAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAsync, []),
            returnValue: _i10.Future<List<_i5.TaskEntity>>.value(
              <_i5.TaskEntity>[],
            ),
          )
          as _i10.Future<List<_i5.TaskEntity>>);

  @override
  _i6.QueryBuilder<_i5.TaskEntity> query([_i6.Condition<_i5.TaskEntity>? qc]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [qc]),
            returnValue: _FakeQueryBuilder_8<_i5.TaskEntity>(
              this,
              Invocation.method(#query, [qc]),
            ),
          )
          as _i6.QueryBuilder<_i5.TaskEntity>);

  @override
  int count({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {#limit: limit}),
            returnValue: 0,
          )
          as int);

  @override
  bool isEmpty() =>
      (super.noSuchMethod(Invocation.method(#isEmpty, []), returnValue: false)
          as bool);

  @override
  bool contains(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool containsMany(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#containsMany, [ids]),
            returnValue: false,
          )
          as bool);

  @override
  bool remove(int? id) =>
      (super.noSuchMethod(Invocation.method(#remove, [id]), returnValue: false)
          as bool);

  @override
  _i10.Future<bool> removeAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  int removeMany(List<int>? ids) =>
      (super.noSuchMethod(Invocation.method(#removeMany, [ids]), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeManyAsync(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#removeManyAsync, [ids]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int removeAll() =>
      (super.noSuchMethod(Invocation.method(#removeAll, []), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllAsync, []),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryBox extends _i1.Mock implements _i6.Box<_i7.CategoryEntity> {
  MockCategoryBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(_i7.CategoryEntity? object, {_i6.PutMode? mode = _i6.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  _i10.Future<int> putAsync(
    _i7.CategoryEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<_i7.CategoryEntity> putAndGetAsync(
    _i7.CategoryEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<_i7.CategoryEntity>.value(
              _FakeCategoryEntity_9(
                this,
                Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i7.CategoryEntity>);

  @override
  _i10.Future<int> putQueuedAwaitResult(
    _i7.CategoryEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueuedAwaitResult, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int putQueued(
    _i7.CategoryEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueued, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  List<int> putMany(
    List<_i7.CategoryEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putMany, [objects], {#mode: mode}),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i10.Future<List<int>> putManyAsync(
    List<_i7.CategoryEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<int>>.value(<int>[]),
          )
          as _i10.Future<List<int>>);

  @override
  _i10.Future<List<_i7.CategoryEntity>> putAndGetManyAsync(
    List<_i7.CategoryEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<_i7.CategoryEntity>>.value(
              <_i7.CategoryEntity>[],
            ),
          )
          as _i10.Future<List<_i7.CategoryEntity>>);

  @override
  _i7.CategoryEntity? get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id]))
          as _i7.CategoryEntity?);

  @override
  _i10.Future<_i7.CategoryEntity?> getAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAsync, [id]),
            returnValue: _i10.Future<_i7.CategoryEntity?>.value(),
          )
          as _i10.Future<_i7.CategoryEntity?>);

  @override
  List<_i7.CategoryEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: <_i7.CategoryEntity?>[],
          )
          as List<_i7.CategoryEntity?>);

  @override
  _i10.Future<List<_i7.CategoryEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManyAsync,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: _i10.Future<List<_i7.CategoryEntity?>>.value(
              <_i7.CategoryEntity?>[],
            ),
          )
          as _i10.Future<List<_i7.CategoryEntity?>>);

  @override
  List<_i7.CategoryEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i7.CategoryEntity>[],
          )
          as List<_i7.CategoryEntity>);

  @override
  _i10.Future<List<_i7.CategoryEntity>> getAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAsync, []),
            returnValue: _i10.Future<List<_i7.CategoryEntity>>.value(
              <_i7.CategoryEntity>[],
            ),
          )
          as _i10.Future<List<_i7.CategoryEntity>>);

  @override
  _i6.QueryBuilder<_i7.CategoryEntity> query([
    _i6.Condition<_i7.CategoryEntity>? qc,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [qc]),
            returnValue: _FakeQueryBuilder_8<_i7.CategoryEntity>(
              this,
              Invocation.method(#query, [qc]),
            ),
          )
          as _i6.QueryBuilder<_i7.CategoryEntity>);

  @override
  int count({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {#limit: limit}),
            returnValue: 0,
          )
          as int);

  @override
  bool isEmpty() =>
      (super.noSuchMethod(Invocation.method(#isEmpty, []), returnValue: false)
          as bool);

  @override
  bool contains(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool containsMany(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#containsMany, [ids]),
            returnValue: false,
          )
          as bool);

  @override
  bool remove(int? id) =>
      (super.noSuchMethod(Invocation.method(#remove, [id]), returnValue: false)
          as bool);

  @override
  _i10.Future<bool> removeAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  int removeMany(List<int>? ids) =>
      (super.noSuchMethod(Invocation.method(#removeMany, [ids]), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeManyAsync(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#removeManyAsync, [ids]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int removeAll() =>
      (super.noSuchMethod(Invocation.method(#removeAll, []), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllAsync, []),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonBox extends _i1.Mock implements _i6.Box<_i8.PersonEntity> {
  MockPersonBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(_i8.PersonEntity? object, {_i6.PutMode? mode = _i6.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  _i10.Future<int> putAsync(
    _i8.PersonEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<_i8.PersonEntity> putAndGetAsync(
    _i8.PersonEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
            returnValue: _i10.Future<_i8.PersonEntity>.value(
              _FakePersonEntity_10(
                this,
                Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i8.PersonEntity>);

  @override
  _i10.Future<int> putQueuedAwaitResult(
    _i8.PersonEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueuedAwaitResult, [object], {#mode: mode}),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int putQueued(
    _i8.PersonEntity? object, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueued, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  List<int> putMany(
    List<_i8.PersonEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putMany, [objects], {#mode: mode}),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i10.Future<List<int>> putManyAsync(
    List<_i8.PersonEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<int>>.value(<int>[]),
          )
          as _i10.Future<List<int>>);

  @override
  _i10.Future<List<_i8.PersonEntity>> putAndGetManyAsync(
    List<_i8.PersonEntity>? objects, {
    _i6.PutMode? mode = _i6.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetManyAsync, [objects], {#mode: mode}),
            returnValue: _i10.Future<List<_i8.PersonEntity>>.value(
              <_i8.PersonEntity>[],
            ),
          )
          as _i10.Future<List<_i8.PersonEntity>>);

  @override
  _i8.PersonEntity? get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id])) as _i8.PersonEntity?);

  @override
  _i10.Future<_i8.PersonEntity?> getAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAsync, [id]),
            returnValue: _i10.Future<_i8.PersonEntity?>.value(),
          )
          as _i10.Future<_i8.PersonEntity?>);

  @override
  List<_i8.PersonEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: <_i8.PersonEntity?>[],
          )
          as List<_i8.PersonEntity?>);

  @override
  _i10.Future<List<_i8.PersonEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManyAsync,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: _i10.Future<List<_i8.PersonEntity?>>.value(
              <_i8.PersonEntity?>[],
            ),
          )
          as _i10.Future<List<_i8.PersonEntity?>>);

  @override
  List<_i8.PersonEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i8.PersonEntity>[],
          )
          as List<_i8.PersonEntity>);

  @override
  _i10.Future<List<_i8.PersonEntity>> getAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAsync, []),
            returnValue: _i10.Future<List<_i8.PersonEntity>>.value(
              <_i8.PersonEntity>[],
            ),
          )
          as _i10.Future<List<_i8.PersonEntity>>);

  @override
  _i6.QueryBuilder<_i8.PersonEntity> query([
    _i6.Condition<_i8.PersonEntity>? qc,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [qc]),
            returnValue: _FakeQueryBuilder_8<_i8.PersonEntity>(
              this,
              Invocation.method(#query, [qc]),
            ),
          )
          as _i6.QueryBuilder<_i8.PersonEntity>);

  @override
  int count({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {#limit: limit}),
            returnValue: 0,
          )
          as int);

  @override
  bool isEmpty() =>
      (super.noSuchMethod(Invocation.method(#isEmpty, []), returnValue: false)
          as bool);

  @override
  bool contains(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool containsMany(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#containsMany, [ids]),
            returnValue: false,
          )
          as bool);

  @override
  bool remove(int? id) =>
      (super.noSuchMethod(Invocation.method(#remove, [id]), returnValue: false)
          as bool);

  @override
  _i10.Future<bool> removeAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  int removeMany(List<int>? ids) =>
      (super.noSuchMethod(Invocation.method(#removeMany, [ids]), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeManyAsync(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#removeManyAsync, [ids]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  int removeAll() =>
      (super.noSuchMethod(Invocation.method(#removeAll, []), returnValue: 0)
          as int);

  @override
  _i10.Future<int> removeAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllAsync, []),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);
}
