// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3IqUxQ_bhtR0j_C3P16NcM4WRn876Q0',
    appId: '1:294414475733:web:26a3a3c5bb8cfca6b39d5c',
    messagingSenderId: '294414475733',
    projectId: 'todolist-4910e',
    authDomain: 'todolist-4910e.firebaseapp.com',
    storageBucket: 'todolist-4910e.firebasestorage.app',
    measurementId: 'G-5VL2STCP9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH6aeFUPIA_R7i8RHXBYsPlKbi06FKNSo',
    appId: '1:294414475733:android:57f2a447249da97eb39d5c',
    messagingSenderId: '294414475733',
    projectId: 'todolist-4910e',
    storageBucket: 'todolist-4910e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6i3ovagMieKQGW9ASN7UR2p_vXlrMneA',
    appId: '1:294414475733:ios:05f146ad28039ecfb39d5c',
    messagingSenderId: '294414475733',
    projectId: 'todolist-4910e',
    storageBucket: 'todolist-4910e.firebasestorage.app',
    iosBundleId: 'com.example.todolistFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6i3ovagMieKQGW9ASN7UR2p_vXlrMneA',
    appId: '1:294414475733:ios:05f146ad28039ecfb39d5c',
    messagingSenderId: '294414475733',
    projectId: 'todolist-4910e',
    storageBucket: 'todolist-4910e.firebasestorage.app',
    iosBundleId: 'com.example.todolistFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN3IqUxQ_bhtR0j_C3P16NcM4WRn876Q0',
    appId: '1:294414475733:web:d0ff54431aa21bafb39d5c',
    messagingSenderId: '294414475733',
    projectId: 'todolist-4910e',
    authDomain: 'todolist-4910e.firebaseapp.com',
    storageBucket: 'todolist-4910e.firebasestorage.app',
    measurementId: 'G-31ZD4PCQB4',
  );
}
