// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/category_entity.dart';
import 'feature/habits/data/models/category_habit_entity.dart';
import 'feature/habits/data/models/habit_entity.dart';
import 'models/person_entity.dart';
import 'feature/tasks/data/task_entity.dart';
import 'models/todo.dart';
import 'models/user_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7505585409734797756),
    name: 'CategoryEntity',
    lastPropertyId: const obx_int.IdUid(2, 1508638993760693042),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5869006530678770595),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1508638993760693042),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'tasks',
        srcEntity: 'TaskEntity',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3261053124586020583),
    name: 'CategoryHabitEntity',
    lastPropertyId: const obx_int.IdUid(5, 4864018437595021041),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2549288460795830472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2481687023556479443),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5546144700584481001),
        name: 'dbColor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2931195964718858625),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4864018437595021041),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'habits',
        srcEntity: 'HabitEntity',
        srcField: 'categoryHabit',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5093207381571386352),
    name: 'HabitEntity',
    lastPropertyId: const obx_int.IdUid(8, 373229210999132242),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3931898100304720553),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 686427302374698433),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1993759774325576428),
        name: 'decription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4864205621582386117),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3180699208528882911),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3832042020228081677),
        name: 'completedDates',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4060205038793638199),
        name: 'titleNormalized',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 181293996281424138),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 373229210999132242),
        name: 'categoryHabitId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2217650783087009412),
        relationField: 'categoryHabit',
        relationTarget: 'CategoryHabitEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5518581724959069876),
    name: 'PersonEntity',
    lastPropertyId: const obx_int.IdUid(2, 5695504262059083665),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4967849210218839409),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5695504262059083665),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'tasks',
        srcEntity: 'TaskEntity',
        srcField: 'person',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3334813013442406372),
    name: 'TaskEntity',
    lastPropertyId: const obx_int.IdUid(14, 5740009727675342557),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4697037864396212622),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7635426773460175986),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4725269071089348403),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8499006132943959115),
        name: 'completed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6930117714248766858),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4600932960851480763),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6696225693908728585),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1448504452909889722),
        name: 'remindMe',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 70319606426264015),
        name: 'link',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3490909070765489788),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2574176743023544534),
        name: 'dbColor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7974356321544396167),
        name: 'titleNormalized',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 5181502334111985466),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3309873219261339131),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 4198986119014632941),
        relationField: 'category',
        relationTarget: 'CategoryEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5740009727675342557),
        name: 'personId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 7510136218335849177),
        relationField: 'person',
        relationTarget: 'PersonEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8905257466848637),
    name: 'Todo',
    lastPropertyId: const obx_int.IdUid(4, 4117188936009372712),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1527866258442827565),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1987078631291455692),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 853736857531133951),
        name: 'isDone',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4117188936009372712),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 731699665393380984),
    name: 'UserModel',
    lastPropertyId: const obx_int.IdUid(4, 3365856474098595131),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6428214400780590504),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 593774511679504510),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 642480065022790790),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3365856474098595131),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 731699665393380984),
    lastIndexId: const obx_int.IdUid(5, 7510136218335849177),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
      model: _entities[0],
      toOneRelations: (CategoryEntity object) => [],
      toManyRelations: (CategoryEntity object) => {
        obx_int.RelInfo<TaskEntity>.toOneBacklink(
          13,
          object.id,
          (TaskEntity srcObject) => srcObject.category,
        ): object.tasks,
      },
      getId: (CategoryEntity object) => object.id,
      setId: (CategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = CategoryEntity(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CategoryEntity>(
          object.tasks,
          store,
          obx_int.RelInfo<TaskEntity>.toOneBacklink(
            13,
            object.id,
            (TaskEntity srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    CategoryHabitEntity: obx_int.EntityDefinition<CategoryHabitEntity>(
      model: _entities[1],
      toOneRelations: (CategoryHabitEntity object) => [],
      toManyRelations: (CategoryHabitEntity object) => {
        obx_int.RelInfo<HabitEntity>.toOneBacklink(
          8,
          object.id,
          (HabitEntity srcObject) => srcObject.categoryHabit,
        ): object.habits,
      },
      getId: (CategoryHabitEntity object) => object.id,
      setId: (CategoryHabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryHabitEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = object.icon == null
            ? null
            : fbb.writeString(object.icon!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dbColor);
        fbb.addOffset(3, iconOffset);
        fbb.addOffset(4, photoPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dbColorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = CategoryHabitEntity(
          name: nameParam,
          dbColor: dbColorParam,
          icon: iconParam,
          photoPath: photoPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CategoryHabitEntity>(
          object.habits,
          store,
          obx_int.RelInfo<HabitEntity>.toOneBacklink(
            8,
            object.id,
            (HabitEntity srcObject) => srcObject.categoryHabit,
          ),
        );
        return object;
      },
    ),
    HabitEntity: obx_int.EntityDefinition<HabitEntity>(
      model: _entities[2],
      toOneRelations: (HabitEntity object) => [object.categoryHabit],
      toManyRelations: (HabitEntity object) => {},
      getId: (HabitEntity object) => object.id,
      setId: (HabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HabitEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final decriptionOffset = object.decription == null
            ? null
            : fbb.writeString(object.decription!);
        final completedDatesOffset = fbb.writeList(
          object.completedDates.map(fbb.writeString).toList(growable: false),
        );
        final titleNormalizedOffset = object.titleNormalized == null
            ? null
            : fbb.writeString(object.titleNormalized!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, decriptionOffset);
        fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endDate.millisecondsSinceEpoch);
        fbb.addOffset(5, completedDatesOffset);
        fbb.addOffset(6, titleNormalizedOffset);
        fbb.addInt64(7, object.categoryHabit.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final decriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final completedDatesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final titleNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = HabitEntity(
          title: titleParam,
          decription: decriptionParam,
          startDate: startDateParam,
          endDate: endDateParam,
          completedDates: completedDatesParam,
          titleNormalized: titleNormalizedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.categoryHabit.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.categoryHabit.attach(store);
        return object;
      },
    ),
    PersonEntity: obx_int.EntityDefinition<PersonEntity>(
      model: _entities[3],
      toOneRelations: (PersonEntity object) => [],
      toManyRelations: (PersonEntity object) => {
        obx_int.RelInfo<TaskEntity>.toOneBacklink(
          14,
          object.id,
          (TaskEntity srcObject) => srcObject.person,
        ): object.tasks,
      },
      getId: (PersonEntity object) => object.id,
      setId: (PersonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PersonEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PersonEntity(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<PersonEntity>(
          object.tasks,
          store,
          obx_int.RelInfo<TaskEntity>.toOneBacklink(
            14,
            object.id,
            (TaskEntity srcObject) => srcObject.person,
          ),
        );
        return object;
      },
    ),
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
      model: _entities[4],
      toOneRelations: (TaskEntity object) => [object.category, object.person],
      toManyRelations: (TaskEntity object) => {},
      getId: (TaskEntity object) => object.id,
      setId: (TaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TaskEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final startTimeOffset = object.startTime == null
            ? null
            : fbb.writeString(object.startTime!);
        final endTimeOffset = object.endTime == null
            ? null
            : fbb.writeString(object.endTime!);
        final linkOffset = object.link == null
            ? null
            : fbb.writeString(object.link!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        final titleNormalizedOffset = object.titleNormalized == null
            ? null
            : fbb.writeString(object.titleNormalized!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.completed);
        fbb.addInt64(4, object.date?.millisecondsSinceEpoch);
        fbb.addOffset(5, startTimeOffset);
        fbb.addOffset(6, endTimeOffset);
        fbb.addBool(7, object.remindMe);
        fbb.addOffset(8, linkOffset);
        fbb.addOffset(9, photoPathOffset);
        fbb.addInt64(10, object.dbColor);
        fbb.addOffset(11, titleNormalizedOffset);
        fbb.addInt64(12, object.category.targetId);
        fbb.addInt64(13, object.person.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final completedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final dateParam = dateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateValue);
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final remindMeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final linkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final titleNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object =
            TaskEntity(
                title: titleParam,
                completed: completedParam,
                description: descriptionParam,
                date: dateParam,
                startTime: startTimeParam,
                endTime: endTimeParam,
                remindMe: remindMeParam,
                link: linkParam,
                photoPath: photoPathParam,
                titleNormalized: titleNormalizedParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..dbColor = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                24,
              );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.category.attach(store);
        object.person.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        object.person.attach(store);
        return object;
      },
    ),
    Todo: obx_int.EntityDefinition<Todo>(
      model: _entities[5],
      toOneRelations: (Todo object) => [],
      toManyRelations: (Todo object) => {},
      getId: (Todo object) => object.id,
      setId: (Todo object, int id) {
        object.id = id;
      },
      objectToFB: (Todo object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addBool(2, object.isDone);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isDoneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = Todo(
          title: titleParam,
          isDone: isDoneParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserModel: obx_int.EntityDefinition<UserModel>(
      model: _entities[6],
      toOneRelations: (UserModel object) => [],
      toManyRelations: (UserModel object) => {},
      getId: (UserModel object) => object.id,
      setId: (UserModel object, int id) {
        object.id = id;
      },
      objectToFB: (UserModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final uidOffset = fbb.writeString(object.uid);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, uidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = UserModel(
          name: nameParam,
          email: emailParam,
          uid: uidParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// See [CategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[0],
  );

  /// See [CategoryEntity.name].
  static final name = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[1],
  );

  /// see [CategoryEntity.tasks]
  static final tasks = obx.QueryBacklinkToMany<TaskEntity, CategoryEntity>(
    TaskEntity_.category,
  );
}

/// [CategoryHabitEntity] entity fields to define ObjectBox queries.
class CategoryHabitEntity_ {
  /// See [CategoryHabitEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryHabitEntity>(
    _entities[1].properties[0],
  );

  /// See [CategoryHabitEntity.name].
  static final name = obx.QueryStringProperty<CategoryHabitEntity>(
    _entities[1].properties[1],
  );

  /// See [CategoryHabitEntity.dbColor].
  static final dbColor = obx.QueryIntegerProperty<CategoryHabitEntity>(
    _entities[1].properties[2],
  );

  /// See [CategoryHabitEntity.icon].
  static final icon = obx.QueryStringProperty<CategoryHabitEntity>(
    _entities[1].properties[3],
  );

  /// See [CategoryHabitEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<CategoryHabitEntity>(
    _entities[1].properties[4],
  );

  /// see [CategoryHabitEntity.habits]
  static final habits =
      obx.QueryBacklinkToMany<HabitEntity, CategoryHabitEntity>(
        HabitEntity_.categoryHabit,
      );
}

/// [HabitEntity] entity fields to define ObjectBox queries.
class HabitEntity_ {
  /// See [HabitEntity.id].
  static final id = obx.QueryIntegerProperty<HabitEntity>(
    _entities[2].properties[0],
  );

  /// See [HabitEntity.title].
  static final title = obx.QueryStringProperty<HabitEntity>(
    _entities[2].properties[1],
  );

  /// See [HabitEntity.decription].
  static final decription = obx.QueryStringProperty<HabitEntity>(
    _entities[2].properties[2],
  );

  /// See [HabitEntity.startDate].
  static final startDate = obx.QueryDateProperty<HabitEntity>(
    _entities[2].properties[3],
  );

  /// See [HabitEntity.endDate].
  static final endDate = obx.QueryDateProperty<HabitEntity>(
    _entities[2].properties[4],
  );

  /// See [HabitEntity.completedDates].
  static final completedDates = obx.QueryStringVectorProperty<HabitEntity>(
    _entities[2].properties[5],
  );

  /// See [HabitEntity.titleNormalized].
  static final titleNormalized = obx.QueryStringProperty<HabitEntity>(
    _entities[2].properties[6],
  );

  /// See [HabitEntity.categoryHabit].
  static final categoryHabit =
      obx.QueryRelationToOne<HabitEntity, CategoryHabitEntity>(
        _entities[2].properties[7],
      );
}

/// [PersonEntity] entity fields to define ObjectBox queries.
class PersonEntity_ {
  /// See [PersonEntity.id].
  static final id = obx.QueryIntegerProperty<PersonEntity>(
    _entities[3].properties[0],
  );

  /// See [PersonEntity.name].
  static final name = obx.QueryStringProperty<PersonEntity>(
    _entities[3].properties[1],
  );

  /// see [PersonEntity.tasks]
  static final tasks = obx.QueryBacklinkToMany<TaskEntity, PersonEntity>(
    TaskEntity_.person,
  );
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.id].
  static final id = obx.QueryIntegerProperty<TaskEntity>(
    _entities[4].properties[0],
  );

  /// See [TaskEntity.title].
  static final title = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[1],
  );

  /// See [TaskEntity.description].
  static final description = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[2],
  );

  /// See [TaskEntity.completed].
  static final completed = obx.QueryBooleanProperty<TaskEntity>(
    _entities[4].properties[3],
  );

  /// See [TaskEntity.date].
  static final date = obx.QueryDateProperty<TaskEntity>(
    _entities[4].properties[4],
  );

  /// See [TaskEntity.startTime].
  static final startTime = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[5],
  );

  /// See [TaskEntity.endTime].
  static final endTime = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[6],
  );

  /// See [TaskEntity.remindMe].
  static final remindMe = obx.QueryBooleanProperty<TaskEntity>(
    _entities[4].properties[7],
  );

  /// See [TaskEntity.link].
  static final link = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[8],
  );

  /// See [TaskEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[9],
  );

  /// See [TaskEntity.dbColor].
  static final dbColor = obx.QueryIntegerProperty<TaskEntity>(
    _entities[4].properties[10],
  );

  /// See [TaskEntity.titleNormalized].
  static final titleNormalized = obx.QueryStringProperty<TaskEntity>(
    _entities[4].properties[11],
  );

  /// See [TaskEntity.category].
  static final category = obx.QueryRelationToOne<TaskEntity, CategoryEntity>(
    _entities[4].properties[12],
  );

  /// See [TaskEntity.person].
  static final person = obx.QueryRelationToOne<TaskEntity, PersonEntity>(
    _entities[4].properties[13],
  );
}

/// [Todo] entity fields to define ObjectBox queries.
class Todo_ {
  /// See [Todo.id].
  static final id = obx.QueryIntegerProperty<Todo>(_entities[5].properties[0]);

  /// See [Todo.title].
  static final title = obx.QueryStringProperty<Todo>(
    _entities[5].properties[1],
  );

  /// See [Todo.isDone].
  static final isDone = obx.QueryBooleanProperty<Todo>(
    _entities[5].properties[2],
  );

  /// See [Todo.createdAt].
  static final createdAt = obx.QueryDateProperty<Todo>(
    _entities[5].properties[3],
  );
}

/// [UserModel] entity fields to define ObjectBox queries.
class UserModel_ {
  /// See [UserModel.id].
  static final id = obx.QueryIntegerProperty<UserModel>(
    _entities[6].properties[0],
  );

  /// See [UserModel.name].
  static final name = obx.QueryStringProperty<UserModel>(
    _entities[6].properties[1],
  );

  /// See [UserModel.email].
  static final email = obx.QueryStringProperty<UserModel>(
    _entities[6].properties[2],
  );

  /// See [UserModel.uid].
  static final uid = obx.QueryStringProperty<UserModel>(
    _entities[6].properties[3],
  );
}
