// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/category_entity.dart';
import 'models/category_habit_entity.dart';
import 'models/habit_entity.dart';
import 'models/person_entity.dart';
import 'models/task_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4591414988621851513),
    name: 'CategoryEntity',
    lastPropertyId: const obx_int.IdUid(2, 297942203221847293),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6606897176521244369),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 297942203221847293),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'tasks',
        srcEntity: 'TaskEntity',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7691265301081398720),
    name: 'PersonEntity',
    lastPropertyId: const obx_int.IdUid(2, 4228620703439142405),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3041772687066064263),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4228620703439142405),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'tasks',
        srcEntity: 'TaskEntity',
        srcField: 'person',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8466330695056283468),
    name: 'TaskEntity',
    lastPropertyId: const obx_int.IdUid(14, 5100381281245120836),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6028198847404881400),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6039604309354184228),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1092364605583308202),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5596549426527702967),
        name: 'completed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2911990382794580769),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 295382349759176738),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 816333813847495278),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2025817754415840546),
        name: 'remindMe',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2769266197057361611),
        name: 'link',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1534225896710723801),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8641778403632885138),
        name: 'dbColor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7474208566134426327),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7204527648223012526),
        relationField: 'category',
        relationTarget: 'CategoryEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8972675162196709951),
        name: 'personId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1801742837880953976),
        relationField: 'person',
        relationTarget: 'PersonEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5100381281245120836),
        name: 'titleNormalized',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 2060406241989216075),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5370743034397862256),
    name: 'CategoryHabitEntity',
    lastPropertyId: const obx_int.IdUid(4, 1275618507017315603),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6947932574169972521),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3130656328865708030),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4219398782557402520),
        name: 'dbColor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1275618507017315603),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'habits',
        srcEntity: 'HabitEntity',
        srcField: 'categoryHabit',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1913945916497946446),
    name: 'HabitEntity',
    lastPropertyId: const obx_int.IdUid(7, 2079892542526941180),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1956169081802511650),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9016253486301210344),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4229195105019603969),
        name: 'decription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2252873426597226188),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6343411330423661416),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6543837992967459087),
        name: 'isCompletedToday',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2079892542526941180),
        name: 'categoryHabitId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 2227868741752588461),
        relationField: 'categoryHabit',
        relationTarget: 'CategoryHabitEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1913945916497946446),
    lastIndexId: const obx_int.IdUid(4, 2227868741752588461),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
      model: _entities[0],
      toOneRelations: (CategoryEntity object) => [],
      toManyRelations: (CategoryEntity object) => {
        obx_int.RelInfo<TaskEntity>.toOneBacklink(
          12,
          object.id,
          (TaskEntity srcObject) => srcObject.category,
        ): object.tasks,
      },
      getId: (CategoryEntity object) => object.id,
      setId: (CategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = CategoryEntity(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CategoryEntity>(
          object.tasks,
          store,
          obx_int.RelInfo<TaskEntity>.toOneBacklink(
            12,
            object.id,
            (TaskEntity srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    PersonEntity: obx_int.EntityDefinition<PersonEntity>(
      model: _entities[1],
      toOneRelations: (PersonEntity object) => [],
      toManyRelations: (PersonEntity object) => {
        obx_int.RelInfo<TaskEntity>.toOneBacklink(
          13,
          object.id,
          (TaskEntity srcObject) => srcObject.person,
        ): object.tasks,
      },
      getId: (PersonEntity object) => object.id,
      setId: (PersonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PersonEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PersonEntity(name: nameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<PersonEntity>(
          object.tasks,
          store,
          obx_int.RelInfo<TaskEntity>.toOneBacklink(
            13,
            object.id,
            (TaskEntity srcObject) => srcObject.person,
          ),
        );
        return object;
      },
    ),
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
      model: _entities[2],
      toOneRelations: (TaskEntity object) => [object.category, object.person],
      toManyRelations: (TaskEntity object) => {},
      getId: (TaskEntity object) => object.id,
      setId: (TaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TaskEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final startTimeOffset = object.startTime == null
            ? null
            : fbb.writeString(object.startTime!);
        final endTimeOffset = object.endTime == null
            ? null
            : fbb.writeString(object.endTime!);
        final linkOffset = object.link == null
            ? null
            : fbb.writeString(object.link!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        final titleNormalizedOffset = object.titleNormalized == null
            ? null
            : fbb.writeString(object.titleNormalized!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.completed);
        fbb.addInt64(4, object.date?.millisecondsSinceEpoch);
        fbb.addOffset(5, startTimeOffset);
        fbb.addOffset(6, endTimeOffset);
        fbb.addBool(7, object.remindMe);
        fbb.addOffset(8, linkOffset);
        fbb.addOffset(9, photoPathOffset);
        fbb.addInt64(10, object.dbColor);
        fbb.addInt64(11, object.category.targetId);
        fbb.addInt64(12, object.person.targetId);
        fbb.addOffset(13, titleNormalizedOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final completedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final dateParam = dateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateValue);
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final remindMeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final linkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final titleNormalizedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final object =
            TaskEntity(
                title: titleParam,
                completed: completedParam,
                description: descriptionParam,
                date: dateParam,
                startTime: startTimeParam,
                endTime: endTimeParam,
                remindMe: remindMeParam,
                link: linkParam,
                photoPath: photoPathParam,
                titleNormalized: titleNormalizedParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..dbColor = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                24,
              );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.category.attach(store);
        object.person.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.person.attach(store);
        return object;
      },
    ),
    CategoryHabitEntity: obx_int.EntityDefinition<CategoryHabitEntity>(
      model: _entities[3],
      toOneRelations: (CategoryHabitEntity object) => [],
      toManyRelations: (CategoryHabitEntity object) => {
        obx_int.RelInfo<HabitEntity>.toOneBacklink(
          7,
          object.id,
          (HabitEntity srcObject) => srcObject.categoryHabit,
        ): object.habits,
      },
      getId: (CategoryHabitEntity object) => object.id,
      setId: (CategoryHabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryHabitEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = object.icon == null
            ? null
            : fbb.writeString(object.icon!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dbColor);
        fbb.addOffset(3, iconOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dbColorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = CategoryHabitEntity(
          name: nameParam,
          dbColor: dbColorParam,
          icon: iconParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CategoryHabitEntity>(
          object.habits,
          store,
          obx_int.RelInfo<HabitEntity>.toOneBacklink(
            7,
            object.id,
            (HabitEntity srcObject) => srcObject.categoryHabit,
          ),
        );
        return object;
      },
    ),
    HabitEntity: obx_int.EntityDefinition<HabitEntity>(
      model: _entities[4],
      toOneRelations: (HabitEntity object) => [object.categoryHabit],
      toManyRelations: (HabitEntity object) => {},
      getId: (HabitEntity object) => object.id,
      setId: (HabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HabitEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final decriptionOffset = object.decription == null
            ? null
            : fbb.writeString(object.decription!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, decriptionOffset);
        fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endDate.millisecondsSinceEpoch);
        fbb.addBool(5, object.isCompletedToday);
        fbb.addInt64(6, object.categoryHabit.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final decriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isCompletedTodayParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = HabitEntity(
          title: titleParam,
          decription: decriptionParam,
          startDate: startDateParam,
          endDate: endDateParam,
          isCompletedToday: isCompletedTodayParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.categoryHabit.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.categoryHabit.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// See [CategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[0],
  );

  /// See [CategoryEntity.name].
  static final name = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[1],
  );

  /// see [CategoryEntity.tasks]
  static final tasks = obx.QueryBacklinkToMany<TaskEntity, CategoryEntity>(
    TaskEntity_.category,
  );
}

/// [PersonEntity] entity fields to define ObjectBox queries.
class PersonEntity_ {
  /// See [PersonEntity.id].
  static final id = obx.QueryIntegerProperty<PersonEntity>(
    _entities[1].properties[0],
  );

  /// See [PersonEntity.name].
  static final name = obx.QueryStringProperty<PersonEntity>(
    _entities[1].properties[1],
  );

  /// see [PersonEntity.tasks]
  static final tasks = obx.QueryBacklinkToMany<TaskEntity, PersonEntity>(
    TaskEntity_.person,
  );
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.id].
  static final id = obx.QueryIntegerProperty<TaskEntity>(
    _entities[2].properties[0],
  );

  /// See [TaskEntity.title].
  static final title = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[1],
  );

  /// See [TaskEntity.description].
  static final description = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[2],
  );

  /// See [TaskEntity.completed].
  static final completed = obx.QueryBooleanProperty<TaskEntity>(
    _entities[2].properties[3],
  );

  /// See [TaskEntity.date].
  static final date = obx.QueryDateProperty<TaskEntity>(
    _entities[2].properties[4],
  );

  /// See [TaskEntity.startTime].
  static final startTime = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[5],
  );

  /// See [TaskEntity.endTime].
  static final endTime = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[6],
  );

  /// See [TaskEntity.remindMe].
  static final remindMe = obx.QueryBooleanProperty<TaskEntity>(
    _entities[2].properties[7],
  );

  /// See [TaskEntity.link].
  static final link = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[8],
  );

  /// See [TaskEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[9],
  );

  /// See [TaskEntity.dbColor].
  static final dbColor = obx.QueryIntegerProperty<TaskEntity>(
    _entities[2].properties[10],
  );

  /// See [TaskEntity.category].
  static final category = obx.QueryRelationToOne<TaskEntity, CategoryEntity>(
    _entities[2].properties[11],
  );

  /// See [TaskEntity.person].
  static final person = obx.QueryRelationToOne<TaskEntity, PersonEntity>(
    _entities[2].properties[12],
  );

  /// See [TaskEntity.titleNormalized].
  static final titleNormalized = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[13],
  );
}

/// [CategoryHabitEntity] entity fields to define ObjectBox queries.
class CategoryHabitEntity_ {
  /// See [CategoryHabitEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryHabitEntity>(
    _entities[3].properties[0],
  );

  /// See [CategoryHabitEntity.name].
  static final name = obx.QueryStringProperty<CategoryHabitEntity>(
    _entities[3].properties[1],
  );

  /// See [CategoryHabitEntity.dbColor].
  static final dbColor = obx.QueryIntegerProperty<CategoryHabitEntity>(
    _entities[3].properties[2],
  );

  /// See [CategoryHabitEntity.icon].
  static final icon = obx.QueryStringProperty<CategoryHabitEntity>(
    _entities[3].properties[3],
  );

  /// see [CategoryHabitEntity.habits]
  static final habits =
      obx.QueryBacklinkToMany<HabitEntity, CategoryHabitEntity>(
        HabitEntity_.categoryHabit,
      );
}

/// [HabitEntity] entity fields to define ObjectBox queries.
class HabitEntity_ {
  /// See [HabitEntity.id].
  static final id = obx.QueryIntegerProperty<HabitEntity>(
    _entities[4].properties[0],
  );

  /// See [HabitEntity.title].
  static final title = obx.QueryStringProperty<HabitEntity>(
    _entities[4].properties[1],
  );

  /// See [HabitEntity.decription].
  static final decription = obx.QueryStringProperty<HabitEntity>(
    _entities[4].properties[2],
  );

  /// See [HabitEntity.startDate].
  static final startDate = obx.QueryDateProperty<HabitEntity>(
    _entities[4].properties[3],
  );

  /// See [HabitEntity.endDate].
  static final endDate = obx.QueryDateProperty<HabitEntity>(
    _entities[4].properties[4],
  );

  /// See [HabitEntity.isCompletedToday].
  static final isCompletedToday = obx.QueryBooleanProperty<HabitEntity>(
    _entities[4].properties[5],
  );

  /// See [HabitEntity.categoryHabit].
  static final categoryHabit =
      obx.QueryRelationToOne<HabitEntity, CategoryHabitEntity>(
        _entities[4].properties[6],
      );
}
